### ISSUE TITLE
feat: Only the current execution context should be reverted if not enough values are on the Stack

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#138]
# Feature Request

**Describe the Feature Request**
Most opcodes modify the state of the current execution context. One important thing is that if there are not enough values on the Stack when executing an opcode (e.g. there is only one value on the Stack and you try to execute ADD), then only the current execution context should be reverted, but the whole tx should not be reverted (as per https://www.evm.codes/ indications).

Currently, using `stack.pop_n()` will revert the entire tx if there are not enough values on the stack.

**Describe Preferred Solution**
TBD

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Eikix** [comment]
Good to know that it exists on Cairo0 codebase: 
We went with the restorative approach rather than accumulator (restorative is: revert loops thru changes and reverts them, accumulator waits to be sure that there's no revert to make the changes)

https://github.com/kkrt-labs/kakarot/blob/9773e4d10a3c3a32fb8aa3cfbf6fdbff35d6985e/src/kakarot/execution_context.cairo#L289

**Comment by Eikix** [comment]
Agreed, let's explore accumulator approach
