### ISSUE TITLE
dev: refactor Exponentiation::pow to always wrap and never panic

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#172]
Currently we have two implementation of the exponent function:
- `pow`: raises to a power, can panic if overflow
- `pow_mod`: raises to a power, does not panic if overflow

We use pow in:
- bitshift: should wrap around
- mask operations: probably should panic as you're not supposed to create a mask that overflows
- opcodes (e.g. EXP): should wrap

Suggestion:
- rename pow_mod into pow for it to become the default power function
- rename pow to pow_unsafe to clearly indicate it can panic in case of overflow

Alternative:
- Just be aware of panic risks, and use pow_mod in most places where wrap around should occur.

**Comment by enitrat** [comment]
> rename pow_mod into pow for it to become the default power function

I don't really like this as I believe the special behavior on overflow should be explicit. `2.pow(257)` should not return `2^2` under any case, as the _real_ intention behind this instruction is to compute the value of $2^{257}$

However, I agree that we could rename `pow_mod` to `wrapping_pow` for consistency with corelib functions (e.g. `u128_wrapping_add` returns the value, whether it has overflown or not) 

To me, it doesn't make sense to use `wrapping_pow` unless this is the expected behavior (so only for specific opcodes). When I compute (2.pow(12)), I don't want it to wrap around if it overflows, as the intention is to get the result of $2^{12}$. However when I compute the `exec_exp `, I explicitly want that value to wrap around, so I will make it clear in the code.

For the rest,
- Bitshifts should not wrap around by default. If you get to that point then it means there's something wrong with your shift
- Same for masks
- Exp should wrap because it's specified as such, therefore we will _explicitly_ use the appropriate function whose name indicates that it wraps

**Comment by Eikix** [comment]
My point is that we're in EVM specific domain, which means that all operations are wrapping around 2^256.
The EVM domain is akin to the Cairo0 Felt concepts, where there aren't overflows, just wrapping around.

I'm in favour of considering that every arithmetic operation in our EVM context wraps around

**Comment by Eikix** [comment]
Wouldn't it be a bit backwards to implement for instance:
a u256 bitshift lib that panics if shift > 255, but for the opcode shr, then implement a bitshift_wide?

**Comment by Eikix** [comment]
Also, another case is that in the memory implementation:
We write for instance:

```let mask_c: u256 = 256.pow(16).into() / mask;```

This is a felt252.pow, that only after the .pow() is performed gets turned into a u256.
But felt252.pow wraps around natively, as Mul<felt252> wraps around

So before the issue/PR, we had two `pow` that behaved differently

**Comment by enitrat** [comment]
> The EVM domain is akin to the Cairo0 Felt concepts, where there aren't overflows, just wrapping around.

Then this wrapping around should be explicit, as it is currently in the core library. I don't want to call `pow` and have wrap around when the intent is either succeed or overflow. If it should wrap around, the function name should reflect this semantic.
This is typically the reason behind integer types in Cairo and why we don't want to perform operations directly on felts: because they might have unintended side effects

>  u256 bitshift lib that panics if shift > 255, but for the opcode shr, then implement a bitshift_wide?

Why not? if the intended behavior of a bitshift is to wrap around, then it should be explicitly stated. Otherwise, you just assume that it can eventually panic on overflow. Then you will use the correct one based on what you're trying to achieve

> This is a felt252.pow, that only after the .pow() is performed gets turned into a u256.
> But felt252.pow wraps around natively, as Mul wraps around

This is true - then it should be casted into a u256 for the operation

**Comment by Eikix** [comment]
Alright:
Incoming changes to the existing PR:

- .pow() will be panic on overflow
- we'll implement wrapping_pow() for felt252 (rename felt252 pow)
- we'll implement bitshift_wide (it doesn't wrap around, it discards bits above 255)
- i'll refactor bitshift to use panic pow
- i'll create wrapping_pow for u256 (rename pow)

**Comment by enitrat** [comment]
sounds good

**Comment by Eikix** [comment]
pushed some improvements
