### ISSUE TITLE
dev: replace all `*_div_rem` by `DivRem::div_rem`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#374]
This improvement makes the codebase lighter by avoiding explicit imports of libfuncs and rely on the trait system to use the correct type

**Comment by khaeljy** [comment]
Can I do it, pls?

**Comment by khaeljy** [comment]
Cause of the `DivRem` trait signature which requires lhs and rhs to be of the same `T` type, I was unable to replace `u512_safe_div_rem_by_u256` which is used here: `crates/evm/src/instructions/stop_and_arithmetic_operations.cairo`

The same applies to the `i256_signed_div_rem` function in `crates/utils/src/i256.cairo`, which takes a `NonZero<u256>` as its second argument, because it's not possible to have a `NonZero<i256>` since `NonZero` is a type defined in the compiler, not in Cairo ( thanks @enitrat ).
