### ISSUE TITLE
dev: test `validate_eth_tx`

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#944]
Write unit tests for https://github.com/kkrt-labs/kakarot-ssj/blob/b1f7f8c13be38edc081f0738c188561240c098b4/crates/evm/src/backend/validation.cairo#L19

You will use the `store` and `load` cheatcodes to set the correct values in storage, and use snforge_std cheatcodes.

Follow the template written in #946

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi, I am Cairo dev with lots of experience contributing to Cairo projects, my OD profile is a witness to this. 

### How I plan on tackling this issue
I would go through the code base and understand the functionality of `validate_eth_tx, after that I would write a robust test ensuring all edge cases are covered and the function behaves as expected.

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I’m also an active member of Dojo Coding, where I'm expanding my skills in Cairo and Web3 technologies. I have previously worked on an issue involving the creation of unit tests in cairo, so I am familiar with the snforge_std cheatcodes and other necessary functions for testing. I’m eager to learn, contribute, and be part of this project.

### How I plan on tackling this issue
 To solve this issue, I would:

1. Follow the template: Since the set_up function to prepare the environment is already defined, I will focus on implementing the various test functions that are outlined.

2. Verify test coverage: I will ensure that the tests work correctly and cover all the functionality.

3. Document my code: Finally, I will document my code for clarity and future reference.
