### ISSUE TITLE
dev: use range operator in for loop

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#977]
https://github.com/kkrt-labs/kakarot-ssj/blob/5352614daf538136ec421ef71a9ae95e64983d29/crates/evm/src/precompiles.cairo#L37-L47

In this function, we use a while loop with a manual increment of the counter `i`.
A more idiomatic approach would be to simply use the range operator documented in the [Cairo Book](https://book.cairo-lang.org/ch02-05-control-flow.html#looping-through-a-collection-with-for)

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
hi

**Comment by fabrobles92** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
My name is Fabricio Robles, I work as a full stack dev since 3 years ago. Also I have been involved in web3 where I have contributed successfully to projects like dojo engine, Concrete and this great project creating some testings. I have experience working with Rust, Cairo, Go, Python and Javascript, I am sure that experience would help me delivering a quality solution for this project

### How I plan on tackling this issue
- I would do a control + find in cairo files searching for while loops
- Understand the context of those loops and analyze if they can be refactored with new loop syntax using ranges (for i in 0..N)
- Apply the refactor
- Run test suite to make sure everything is working.
- PR

**Comment by enitrat** [comment]
superceded by https://github.com/kkrt-labs/kakarot-ssj/issues/978
